SELECT ?label WHERE {
  ?keyword wdt:P279 ?subclass .
  ?subclass wdt:P279 wd:Q28654074 .
  ?keyword rdfs:label ?label FILTER (lang(?label) = "fr") .
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],fr". }
}
