SELECT ?label WHERE {
  ?keyword wdt:P31 wd:Q930752 .
  ?keyword rdfs:label ?label FILTER (lang(?label) = "fr") .
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],fr". }
}
