SELECT DISTINCT ?label WHERE {
  ?keyword wdt:P923 ?obj .
  ?obj rdfs:label ?label FILTER (lang(?label) = "fr") .
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],fr". }
}
