SELECT DISTINCT ?label WHERE {
  ?sim wdt:P279 wd:Q179661 .
  ?sim rdfs:label ?label FILTER (lang(?label) = "uk") .
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],uk". }
}
