SELECT ?label WHERE {
  ?keyword wdt:P31 wd:Q112193867 .
  ?keyword rdfs:label ?label FILTER (lang(?label) = "uk") .
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],uk". }
}
